### PR TITLE
adds support for isc/dshield query of an ip address

### PR DESCRIPTION
**Pull request by jeffbryner**
spare time on a sunday to contribute the 'lil code attached herein.

### CODE REVIEW

**Comment by krmaxwell** [comment]
No test? :(

**Comment by jeffbryner** [comment]
I tested it, it works...trust me :-)

On May 3, 2015 5:32:05 PM PDT, Kyle Maxwell <notifications@github.com> wrote:
>No test? :( 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/yolothreat/utilitybelt/pull/44#issuecomment-98560261

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jeffbryner** [comment]
test added

**Comment by sroberts** [comment]
Did something break CI?

**Comment by krmaxwell** [comment]
It's a PR and not in our repo. That should be semi-fixed momentarily when I pull it into a branch from his fork.

#lrn2github

**Comment by sroberts** [comment]
Hmmmm that seems like a config issue. It should be doing that.

**Comment by krmaxwell** [comment]
Passes now, still at :100: % coverage, no linter issues.

:+1:

**Pull request merged**
