### PR TITLE
Get tests passing

### LINKED ISSUE #24: Tests aren't passing.
This is sort of an obvious one.

### LINKED ISSUE #27: Project engineering
Now that existing tests are passing, we need a few more things:

- [x] Waffle.io board
- [x] Pre-commit setup
- [x] Code coverage testing
- [x] Landscape.io code quality testing
- [x] Stinking badges

### LINKED ISSUE #29: Raise code coverage
- [x]  Reserved addresses in 172.16.0.0/16
- [x] Addresses in 169.254.0.0/12
- [x] reverse_dns_sna()

### PR DESCRIPTION
**Pull request by krmaxwell**
Close #24 - note this will also include #25 
Close #27 
Close #29

### CODE REVIEW

**Comment by krmaxwell** [comment]
Hrm. Green on my end.

**Comment by krmaxwell** [comment]
:crown: :hankey:

**Comment by krmaxwell** [comment]
89% coverage? Damn, better than I expected.

**Comment by krmaxwell** [comment]
YOLOMERGE

**Comment by sroberts** [comment]
YOLO

**Pull request merged**
