### PR TITLE
VT API additions

### LINKED ISSUE #51: `vt_name_check()` and `vt_api_check()` do not handle errors properly
If VirusTotal returns an error (such as exceeding rate limits), these functions throw a `JSONDecodeError`.

### LINKED ISSUE #52: Virustotal method for files
Get data for a hash

### PR DESCRIPTION
**Pull request by krmaxwell**
- Close #51 by catching ValueError
- Close #52 by implementing vt_hash_check()

### CODE REVIEW

**Comment by krmaxwell** [comment]
Hrm, we might actually have an issue with `re_ssdeep` because I grabbed the test case directly from http://ssdeep.sourceforge.net/usage.html

**Comment by krmaxwell** [comment]
Derp, no. I found the problem with the test.

**Comment by sroberts** [comment]
Figured it out?

**Comment by krmaxwell** [comment]
Yes, `re_ssdeep` is fine (I had forgotten to include the block size in the string passed to `is_hash()`. Testing will take longer now because we wait 15 seconds after each test that calls the VirusTotal API (since there's a limit on calls to the public API). However, we also have a test to check for that rate limiting.

Are you happy with the design of `is_hash()`, where it just returns `True` if the string matches any of the hash regexes? I feel like a user can always just use the specific regex if they want to test for a particular type.

**Comment by krmaxwell** [comment]
Any :+1: / :-1: on this?

**Comment by sroberts** [comment]
This looks killer.

**Pull request merged**
